/**
 * Hostile DashboardPayload fixture for frontend development.
 *
 * Deliberately exercises every edge case the UI must render distinctly:
 * stale / unknown prices, null 1M history, incomplete timeframe history,
 * empty activity, and insights of all four types across all three categories.
 *
 * Typed strictly against contract.ts — do not "fix" shapes here.
 */

import type {
  ActivityPayload,
  DashboardPayload,
  InsightEvent,
  PerformancePoint,
  PortfolioAllocation,
  PortfolioPerformance,
  PortfolioSummary,
  Position,
  PositionsPayload,
  SyncStatusPayload,
  ValueChange,
} from "@/lib/dashboard/contract"

const SNAPSHOT_ID = "snap_fixture_01hzhostile"
const AS_OF = "2026-08-16T04:20:00Z"
const END_DATE = "2026-08-15"

function nullChangeMap(
  overrides: Partial<Record<"7D" | "1M" | "3M" | "6M" | "1Y" | "MAX", number | null>> = {}
): Position["valueChangePct"] {
  return {
    "7D": null,
    "1M": null,
    "3M": null,
    "6M": null,
    "1Y": null,
    MAX: null,
    ...overrides,
  }
}

const summary: PortfolioSummary = {
  totalValue: 48_752_40,
  costBasis: 41_200_00,
  unrealizedPnl: 7_552_40,
  unrealizedPnlPct: 0.1833,
  realizedPnl: 1_240_50,
  netCashFlow: -39_959_50,
  totalInvested: 52_100_00,
  totalProceeds: 12_140_50,
  positionCount: 8,
  unitCount: 47,
  pricedPositionCount: 6,
  stalePositionCount: 1,
  unknownPositionCount: 1,
}

const timeframes: ValueChange[] = [
  {
    timeframe: "7D",
    startDate: "2026-08-08",
    endDate: END_DATE,
    startValue: 47_100_00,
    endValue: 48_752_40,
    valueChangeAbs: 1_652_40,
    valueChangePct: 0.0351,
    hasFullHistory: true,
  },
  {
    timeframe: "1M",
    startDate: "2026-07-16",
    endDate: END_DATE,
    startValue: 44_200_00,
    endValue: 48_752_40,
    valueChangeAbs: 4_552_40,
    valueChangePct: 0.103,
    hasFullHistory: true,
  },
  {
    timeframe: "3M",
    startDate: "2026-05-16",
    endDate: END_DATE,
    startValue: 39_800_00,
    endValue: 48_752_40,
    valueChangeAbs: 8_952_40,
    valueChangePct: 0.2249,
    hasFullHistory: true,
  },
  {
    timeframe: "6M",
    // History only goes back ~4 months — incomplete window.
    startDate: "2026-04-02",
    endDate: END_DATE,
    startValue: 36_500_00,
    endValue: 48_752_40,
    valueChangeAbs: 12_252_40,
    valueChangePct: 0.3357,
    hasFullHistory: false,
  },
  {
    timeframe: "1Y",
    startDate: "2026-04-02",
    endDate: END_DATE,
    startValue: 36_500_00,
    endValue: 48_752_40,
    valueChangeAbs: 12_252_40,
    valueChangePct: 0.3357,
    hasFullHistory: false,
  },
  {
    timeframe: "MAX",
    startDate: "2026-04-02",
    endDate: END_DATE,
    startValue: 36_500_00,
    endValue: 48_752_40,
    valueChangeAbs: 12_252_40,
    valueChangePct: 0.3357,
    hasFullHistory: true,
  },
]

/** Actual vs projected series that cross — meaningful, not a bug (PRD §16). */
function buildSeries(): PerformancePoint[] {
  const points: PerformancePoint[] = []
  const start = new Date("2026-07-16T00:00:00Z")
  for (let i = 0; i < 31; i++) {
    const d = new Date(start)
    d.setUTCDate(start.getUTCDate() + i)
    const date = d.toISOString().slice(0, 10)
    // Actual rises with a mid-window buy bump; projected is smoother and crosses.
    const t = i / 30
    const actualBase = 44200 + t * 3500 + Math.sin(t * Math.PI * 2) * 400
    const projectedBase = 45800 + t * 1800 + Math.cos(t * Math.PI * 2) * 600
    // Gap day mid-series on actual to exercise connectNulls:false
    const gap = i === 14
    points.push({
      date,
      actual: gap ? null : Math.round(actualBase * 100),
      projected: Math.round(projectedBase * 100),
    })
  }
  return points
}

const performance: PortfolioPerformance = {
  timeframes,
  seriesTimeframe: "1M",
  series: buildSeries(),
}

const positions: Position[] = [
  {
    productId: "prod_sea_sky",
    name: "Sea & Sky Premium Collection",
    setId: "set_sv8",
    setName: "Surging Sparks",
    tcgplayerId: "566112",
    category: "Collection Box",
    categorySource: "inferred",
    quantity: 4,
    currentUnitPrice: 251_00,
    marketValue: 10_040_00,
    costBasis: 7_200_00,
    avgUnitCost: 180_00,
    unrealizedPnl: 2_840_00,
    unrealizedPnlPct: 0.3944,
    realizedPnl: 0,
    valueChangePct: nullChangeMap({
      "7D": 0.012,
      "1M": 0.082,
      "3M": 0.21,
      "6M": 0.35,
      "1Y": 0.35,
      MAX: 0.41,
    }),
    signal: "Accelerating",
    priceStatus: "ok",
    lastPricedAt: "2026-08-15",
    portfolioShare: 0.206,
    holdingPeriod: {
      valueWeightedAgeDays: 210,
      oldestOpenLotDate: "2025-11-02",
      oldestOpenLotAgeDays: 287,
      lotsApproachingOneYear: 1,
    },
    trackedAth: 260_00,
    trackedAthDate: "2026-07-01",
    drawdownFromAthPct: -0.0346,
  },
  {
    productId: "prod_blooming",
    name: "Blooming Waters Premium Collection",
    setId: "set_sv7",
    setName: "Stellar Crown",
    tcgplayerId: "554433",
    category: "Collection Box",
    categorySource: "inferred",
    quantity: 3,
    currentUnitPrice: 198_50,
    marketValue: 5_955_00,
    costBasis: 6_900_00,
    avgUnitCost: 230_00,
    unrealizedPnl: -945_00,
    unrealizedPnlPct: -0.137,
    realizedPnl: 0,
    valueChangePct: nullChangeMap({
      "7D": -0.041,
      "1M": -0.1465,
      "3M": -0.22,
      "6M": -0.18,
      "1Y": -0.18,
      MAX: -0.12,
    }),
    signal: "Declining",
    priceStatus: "ok",
    lastPricedAt: "2026-08-15",
    portfolioShare: 0.1221,
    holdingPeriod: {
      valueWeightedAgeDays: 140,
      oldestOpenLotDate: "2026-02-10",
      oldestOpenLotAgeDays: 186,
      lotsApproachingOneYear: 0,
    },
    trackedAth: 245_00,
    trackedAthDate: "2026-04-20",
    drawdownFromAthPct: -0.1898,
  },
  {
    productId: "prod_v_heroes",
    name: "V Heroes Tin [Espeon V]",
    setId: "set_swsh",
    setName: "Sword & Shield",
    tcgplayerId: "235001",
    category: "Tin",
    categorySource: "inferred",
    quantity: 6,
    currentUnitPrice: 42_00,
    marketValue: 2_520_00,
    costBasis: 2_100_00,
    avgUnitCost: 35_00,
    unrealizedPnl: 420_00,
    unrealizedPnlPct: 0.2,
    realizedPnl: 80_00,
    valueChangePct: nullChangeMap({
      "7D": 0.035,
      "1M": 0.118,
      "3M": 0.05,
      "6M": -0.02,
      "1Y": -0.02,
      MAX: 0.08,
    }),
    signal: "Recovering",
    priceStatus: "ok",
    lastPricedAt: "2026-08-15",
    portfolioShare: 0.0517,
    holdingPeriod: {
      valueWeightedAgeDays: 320,
      oldestOpenLotDate: "2025-09-01",
      oldestOpenLotAgeDays: 349,
      lotsApproachingOneYear: 2,
    },
    trackedAth: 48_00,
    trackedAthDate: "2025-12-01",
    drawdownFromAthPct: -0.125,
  },
  {
    productId: "prod_prismatic_etb",
    name: "Prismatic Evolutions Elite Trainer Box",
    setId: "set_sv8pt5",
    setName: "Prismatic Evolutions",
    tcgplayerId: "566890",
    category: "ETB",
    categorySource: "inferred",
    quantity: 5,
    // Stale: last known-good price still contributes to totals.
    currentUnitPrice: 89_00,
    marketValue: 4_450_00,
    costBasis: 3_750_00,
    avgUnitCost: 75_00,
    unrealizedPnl: 700_00,
    unrealizedPnlPct: 0.1867,
    realizedPnl: 0,
    valueChangePct: nullChangeMap({
      "7D": 0.01,
      "1M": 0.045,
      "3M": 0.12,
      "6M": 0.28,
      "1Y": 0.28,
      MAX: 0.33,
    }),
    signal: "Cooling",
    priceStatus: "stale",
    lastPricedAt: "2026-08-01",
    portfolioShare: 0.0913,
    holdingPeriod: {
      valueWeightedAgeDays: 95,
      oldestOpenLotDate: "2026-05-01",
      oldestOpenLotAgeDays: 106,
      lotsApproachingOneYear: 0,
    },
    trackedAth: 95_00,
    trackedAthDate: "2026-07-10",
    drawdownFromAthPct: -0.0632,
  },
  {
    productId: "prod_unknown_price",
    name: "Mystery Bundle — Untracked Reprint",
    setId: "set_misc",
    setName: "Miscellaneous",
    tcgplayerId: null,
    category: "Uncategorized",
    categorySource: "inferred",
    quantity: 2,
    currentUnitPrice: null,
    // Contract: 0 only when genuinely unknown.
    marketValue: 0,
    costBasis: 800_00,
    avgUnitCost: 400_00,
    unrealizedPnl: -800_00,
    unrealizedPnlPct: null,
    realizedPnl: 0,
    valueChangePct: nullChangeMap(),
    signal: "Insufficient data",
    priceStatus: "unknown",
    lastPricedAt: null,
    portfolioShare: 0,
    holdingPeriod: {
      valueWeightedAgeDays: null,
      oldestOpenLotDate: "2026-06-01",
      oldestOpenLotAgeDays: 75,
      lotsApproachingOneYear: 0,
    },
    trackedAth: null,
    trackedAthDate: null,
    drawdownFromAthPct: null,
  },
  {
    productId: "prod_no_history",
    name: "Destined Rivals Booster Bundle",
    setId: "set_sv10",
    setName: "Destined Rivals",
    tcgplayerId: "601122",
    category: "Booster Bundle",
    categorySource: "override",
    quantity: 8,
    currentUnitPrice: 32_50,
    marketValue: 2_600_00,
    costBasis: 2_400_00,
    avgUnitCost: 30_00,
    unrealizedPnl: 200_00,
    unrealizedPnlPct: 0.0833,
    realizedPnl: 0,
    // Has current price but no 1M history → heatmap Unknown, not 0%.
    valueChangePct: nullChangeMap({
      "7D": 0.02,
      "1M": null,
      "3M": null,
      "6M": null,
      "1Y": null,
      MAX: 0.02,
    }),
    signal: "Insufficient data",
    priceStatus: "ok",
    lastPricedAt: "2026-08-15",
    portfolioShare: 0.0533,
    holdingPeriod: {
      valueWeightedAgeDays: 12,
      oldestOpenLotDate: "2026-08-03",
      oldestOpenLotAgeDays: 12,
      lotsApproachingOneYear: 0,
    },
    trackedAth: 32_50,
    trackedAthDate: "2026-08-15",
    drawdownFromAthPct: 0,
  },
  {
    productId: "prod_surging_bb",
    name: "Surging Sparks Booster Box",
    setId: "set_sv8",
    setName: "Surging Sparks",
    tcgplayerId: "566100",
    category: "Booster Box",
    categorySource: "inferred",
    quantity: 2,
    currentUnitPrice: 8_400_00,
    marketValue: 16_800_00,
    costBasis: 14_200_00,
    avgUnitCost: 7_100_00,
    unrealizedPnl: 2_600_00,
    unrealizedPnlPct: 0.1831,
    realizedPnl: 1_160_50,
    valueChangePct: nullChangeMap({
      "7D": 0.008,
      "1M": 0.062,
      "3M": 0.15,
      "6M": 0.29,
      "1Y": 0.29,
      MAX: 0.38,
    }),
    signal: "Cooling",
    priceStatus: "ok",
    lastPricedAt: "2026-08-15",
    portfolioShare: 0.3446,
    holdingPeriod: {
      valueWeightedAgeDays: 180,
      oldestOpenLotDate: "2025-12-20",
      oldestOpenLotAgeDays: 238,
      lotsApproachingOneYear: 0,
    },
    trackedAth: 8_600_00,
    trackedAthDate: "2026-06-15",
    drawdownFromAthPct: -0.0233,
  },
  {
    productId: "prod_paldean_blister",
    name: "Paldean Fates Tech Sticker Blister",
    setId: "set_sv4pt5",
    setName: "Paldean Fates",
    tcgplayerId: "541200",
    category: "Blister",
    categorySource: "inferred",
    quantity: 10,
    currentUnitPrice: 18_87,
    marketValue: 1_887_00,
    costBasis: 1_650_00,
    avgUnitCost: 16_50,
    unrealizedPnl: 237_00,
    unrealizedPnlPct: 0.1436,
    realizedPnl: 0,
    valueChangePct: nullChangeMap({
      "7D": -0.015,
      "1M": -0.032,
      "3M": 0.04,
      "6M": 0.11,
      "1Y": 0.11,
      MAX: 0.19,
    }),
    signal: "Declining",
    priceStatus: "ok",
    lastPricedAt: "2026-08-15",
    portfolioShare: 0.0387,
    holdingPeriod: {
      valueWeightedAgeDays: 260,
      oldestOpenLotDate: "2025-10-15",
      oldestOpenLotAgeDays: 305,
      lotsApproachingOneYear: 0,
    },
    trackedAth: 22_00,
    trackedAthDate: "2026-03-01",
    drawdownFromAthPct: -0.1423,
  },
]

const positionsPayload: PositionsPayload = {
  positions,
  heatmapColorDomain: { min: -0.25, max: 0.25 },
}

const allocation: PortfolioAllocation = {
  totalValue: 48_752_40,
  bySet: [
    { key: "set_sv8", label: "Surging Sparks", value: 26_840_00, share: 0.5505, positionCount: 2 },
    { key: "set_sv7", label: "Stellar Crown", value: 5_955_00, share: 0.1221, positionCount: 1 },
    { key: "set_sv8pt5", label: "Prismatic Evolutions", value: 4_450_00, share: 0.0913, positionCount: 1 },
    { key: "set_sv10", label: "Destined Rivals", value: 2_600_00, share: 0.0533, positionCount: 1 },
    { key: "set_swsh", label: "Sword & Shield", value: 2_520_00, share: 0.0517, positionCount: 1 },
    { key: "set_sv4pt5", label: "Paldean Fates", value: 1_887_00, share: 0.0387, positionCount: 1 },
    { key: "set_misc", label: "Miscellaneous", value: 0, share: 0, positionCount: 1 },
  ],
  byCategory: [
    { key: "Booster Box", label: "Booster Box", value: 16_800_00, share: 0.3446, positionCount: 1 },
    { key: "Collection Box", label: "Collection Box", value: 15_995_00, share: 0.3281, positionCount: 2 },
    { key: "ETB", label: "ETB", value: 4_450_00, share: 0.0913, positionCount: 1 },
    { key: "Booster Bundle", label: "Booster Bundle", value: 2_600_00, share: 0.0533, positionCount: 1 },
    { key: "Tin", label: "Tin", value: 2_520_00, share: 0.0517, positionCount: 1 },
    { key: "Blister", label: "Blister", value: 1_887_00, share: 0.0387, positionCount: 1 },
    { key: "Uncategorized", label: "Uncategorized", value: 0, share: 0, positionCount: 1 },
  ],
}

/** Empty activity — hostile case for the Recent activity empty state. */
const activity: ActivityPayload = {
  items: [],
  totalCount: 0,
}

/** Non-empty sample for tests / Story-style rendering checks. */
export const ACTIVITY_WITH_ITEMS: ActivityPayload = {
  totalCount: 14,
  items: [
    {
      transactionId: "tx_1",
      portfolioId: "pf_main",
      portfolioName: "Main",
      productId: "prod_surging_bb",
      productName: "Surging Sparks Booster Box",
      setName: "Surging Sparks",
      type: "buy",
      quantity: 1,
      unitPrice: 7_100_00,
      totalAmount: 7_100_00,
      date: "2026-08-10",
      realizedPnl: null,
      notes: null,
    },
    {
      transactionId: "tx_2",
      portfolioId: "pf_main",
      portfolioName: "Main",
      productId: "prod_v_heroes",
      productName: "V Heroes Tin [Espeon V]",
      setName: "Sword & Shield",
      type: "sell",
      quantity: 2,
      unitPrice: 40_00,
      totalAmount: 80_00,
      date: "2026-08-05",
      realizedPnl: 80_00,
      notes: "Trimmed duplicate",
    },
    {
      transactionId: "tx_3",
      portfolioId: "pf_main",
      portfolioName: "Main",
      productId: "prod_no_history",
      productName: "Destined Rivals Booster Bundle",
      setName: "Destined Rivals",
      type: "buy",
      quantity: 8,
      unitPrice: 30_00,
      totalAmount: 2_400_00,
      date: "2026-08-03",
      realizedPnl: null,
      notes: null,
    },
  ],
}

const insights: InsightEvent[] = [
  {
    id: "ins_conc_1",
    type: "concentration",
    category: "needs_attention",
    state: "active",
    severity: 60 + 0.6, // 60 + excess over 20%
    entityId: "prod_sea_sky",
    entityName: "Sea & Sky Premium Collection",
    setName: "Surging Sparks",
    headline: "Concentration: Sea & Sky Premium Collection — 20.6% of portfolio",
    detail: "Share crossed the 20% threshold.",
    triggeredAt: "2026-08-14T12:00:00Z",
    resolvedAt: null,
    seenAt: null,
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "concentration:prod_sea_sky:2026-08-14",
    payload: {
      kind: "concentration",
      sharePct: 0.206,
      thresholdPct: 0.2,
    },
  },
  {
    id: "ins_out_down",
    type: "outsized_move",
    category: "needs_attention",
    state: "active",
    severity: 50 + 14.65,
    entityId: "prod_blooming",
    entityName: "Blooming Waters Premium Collection",
    setName: "Stellar Crown",
    headline: "Outsized move down: Blooming Waters — −14.65% (1M)",
    detail: null,
    triggeredAt: "2026-08-13T09:00:00Z",
    resolvedAt: null,
    seenAt: null,
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "outsized:prod_blooming:down:1M",
    payload: {
      kind: "outsized_move",
      direction: "down",
      movePct: -0.1465,
      timeframe: "1M",
      fromState: "NORMAL",
      toState: "OUTSIZED_DOWN",
    },
  },
  {
    id: "ins_drawdown",
    type: "drawdown",
    category: "needs_attention",
    state: "active",
    severity: 40 + 18.98,
    entityId: "prod_blooming",
    entityName: "Blooming Waters Premium Collection",
    setName: "Stellar Crown",
    headline: "Drawdown: Blooming Waters — −18.98% from Tracked ATH",
    detail: "Tracked ATH $245.00 on Apr 20, 2026.",
    triggeredAt: "2026-08-12T09:00:00Z",
    resolvedAt: null,
    seenAt: "2026-08-12T18:00:00Z",
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "drawdown:prod_blooming",
    payload: {
      kind: "drawdown",
      drawdownPct: -0.1898,
      thresholdPct: 0.15,
      trackedAth: 245_00,
      trackedAthDate: "2026-04-20",
    },
  },
  {
    id: "ins_sig_neg",
    type: "signal_transition",
    category: "needs_attention",
    state: "active",
    severity: 70,
    entityId: "prod_paldean_blister",
    entityName: "Paldean Fates Tech Sticker Blister",
    setName: "Paldean Fates",
    headline: "Declining: Paldean Fates Tech Sticker Blister",
    detail: "Cooling → Declining",
    triggeredAt: "2026-08-11T09:00:00Z",
    resolvedAt: null,
    seenAt: null,
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "signal:prod_paldean_blister:Cooling:Declining",
    payload: {
      kind: "signal_transition",
      fromSignal: "Cooling",
      toSignal: "Declining",
    },
  },
  {
    id: "ins_out_up",
    type: "outsized_move",
    category: "positive",
    state: "active",
    severity: 30 + 11.8,
    entityId: "prod_v_heroes",
    entityName: "V Heroes Tin [Espeon V]",
    setName: "Sword & Shield",
    headline: "Outsized move up: V Heroes Tin [Espeon V] — +11.8% (1M)",
    detail: null,
    triggeredAt: "2026-08-10T09:00:00Z",
    resolvedAt: null,
    seenAt: null,
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "outsized:prod_v_heroes:up:1M",
    payload: {
      kind: "outsized_move",
      direction: "up",
      movePct: 0.118,
      timeframe: "1M",
      fromState: "NORMAL",
      toState: "OUTSIZED_UP",
    },
  },
  {
    id: "ins_sig_pos",
    type: "signal_transition",
    category: "positive",
    state: "resolved",
    severity: 35,
    entityId: "prod_v_heroes",
    entityName: "V Heroes Tin [Espeon V]",
    setName: "Sword & Shield",
    headline: "Recovering: V Heroes Tin [Espeon V]",
    detail: "Declining → Recovering",
    triggeredAt: "2026-08-09T09:00:00Z",
    resolvedAt: "2026-08-09T09:00:00Z",
    seenAt: "2026-08-09T12:00:00Z",
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "signal:prod_v_heroes:Declining:Recovering",
    payload: {
      kind: "signal_transition",
      fromSignal: "Declining",
      toSignal: "Recovering",
    },
  },
  {
    id: "ins_sig_neutral",
    type: "signal_transition",
    category: "signal_change",
    state: "active",
    severity: 35,
    entityId: "prod_prismatic_etb",
    entityName: "Prismatic Evolutions Elite Trainer Box",
    setName: "Prismatic Evolutions",
    headline: "Cooling: Prismatic Evolutions Elite Trainer Box",
    detail: "Accelerating → Cooling",
    triggeredAt: "2026-08-08T09:00:00Z",
    resolvedAt: null,
    seenAt: null,
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "signal:prod_prismatic_etb:Accelerating:Cooling",
    payload: {
      kind: "signal_transition",
      fromSignal: "Accelerating",
      toSignal: "Cooling",
    },
  },
  {
    id: "ins_sig_neutral_2",
    type: "signal_transition",
    category: "signal_change",
    state: "active",
    severity: 35,
    entityId: "prod_surging_bb",
    entityName: "Surging Sparks Booster Box",
    setName: "Surging Sparks",
    headline: "Cooling: Surging Sparks Booster Box",
    detail: "Accelerating → Cooling",
    triggeredAt: "2026-08-07T09:00:00Z",
    resolvedAt: null,
    seenAt: "2026-08-07T15:00:00Z",
    snapshotId: SNAPSHOT_ID,
    dedupeKey: "signal:prod_surging_bb:Accelerating:Cooling",
    payload: {
      kind: "signal_transition",
      fromSignal: "Accelerating",
      toSignal: "Cooling",
    },
  },
]

const sync: SyncStatusPayload = {
  state: "partially_priced",
  lastAttemptedAt: "2026-08-16T04:00:00Z",
  lastAttemptStatus: "partial",
  lastSuccessfulAt: "2026-08-16T04:00:00Z",
  productsTotal: 8,
  productsSynced: 6,
  productsFailed: 2,
  failures: [
    {
      productId: "prod_prismatic_etb",
      name: "Prismatic Evolutions Elite Trainer Box",
      reason: "TCGPlayer rate limit",
    },
    {
      productId: "prod_unknown_price",
      name: "Mystery Bundle — Untracked Reprint",
      reason: "No TCGPlayer mapping",
    },
  ],
  stalePositionCount: 1,
  nextScheduledDescription: "Wed 5:00 AM ET",
}

/**
 * Full hostile payload. Severity already descending as the API must return.
 * Display cap of 5 is a UI concern only — all 8 events are present.
 */
export const DASHBOARD_FIXTURE: DashboardPayload = {
  summary,
  performance,
  positions: positionsPayload,
  allocation,
  activity,
  insights: {
    events: [...insights].sort((a, b) => b.severity - a.severity),
    activeCount: insights.filter((e) => e.state === "active").length,
    unseenCount: insights.filter((e) => e.state === "active" && e.seenAt == null).length,
    totalCount: insights.length,
  },
  sync,
}

export const FIXTURE_ENVELOPE = {
  asOf: AS_OF,
  snapshotId: SNAPSHOT_ID,
  currency: "USD" as const,
  data: DASHBOARD_FIXTURE,
}
